### ISSUE TITLE
Allow definition of required templates 

### ISSUE THREAD

**Issue by sibille** [Microsoft/CoreTemplateStudio#182]
Currently dependencies can be set only to a specific templateId.
The securized WebAPI feature from WinTS has a dependency on adding a Login Feature, but there are currently two flavors (Forced and Optional Login). 

We should allow the possibility to define alternatives for dependencies.

**Comment by mrlacey** [comment]
Calling these dependencies is potentially confusing.
Currently a dependency is something that must also be included with an item.

Here, it seems that this should only be available if another item has already be selected.
Can we call this a requirement or "required template" instead?

I'm not just being pedantic about semantics. I'm just trying to avoid confusion.
I had to read the OP several times to understand that this was something different to current dependencies.

**Comment by sibille** [comment]
I think I didn't explain myself correctly. 
Securized WebApi will add the Optional Login as a dependency when you select it, you don't have to select it first. It is a dependency, because we need it to be there because the feature will do changes to the IdentityService. 
The problem is that OptionalLogin isn't the only valid option for this dependency, Forced Login is a valid alternative, we should give the oportunity to choose Securized WebAPI with forced login too.

**Comment by mrlacey** [comment]
Because this is doing something different, I wanted to use different terms.

So, dependencies automatically select the other items when chosen.

Instead, this (Securized Web API) should (can) only be selected when one of the other ("requirements") is already selected. 

I'm imagining that if you try and select an item where one of the "requirements" is not already selected a warning message is displayed saying you need to select one of the other items first.

This seems a simpler approach than asking which of the other items to select when trying to add the new option and not having already selected a login option.

**Comment by sibille** [comment]
Makes sense, as we allow the user to choose which identity template to select before adding Securized Web API.

**Comment by sibille** [comment]
Verified in WinTS dev-nightly: 
Templates version: 0.20.19280.1
Wizard version: 0.20.19278.1
